name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Verify gradlew file exists
      run: |
        if [ ! -f ./gradlew ]; then
          echo "gradlew file not found!"
          exit 1
        fi

    - name: Display Gradle version
      run: ./gradlew --version  # Check if Gradle wrapper is set up properly

    - name: Build with Gradle
      run: ./gradlew build --no-daemon --stacktrace  # --stacktrace to get detailed error logs

    # Optionally, run tests to validate the build
    - name: Run Unit Tests
      run: ./gradlew test --no-daemon --stacktrace
