name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean Gradle Build
      run: ./gradlew clean  # Clean build before starting

    - name: Verify gradlew file exists
      run: |
        if [ ! -f ./gradlew ]; then
          echo "gradlew file not found!"
          exit 1
        fi

    - name: Build APK
      run: ./gradlew assembleDebug  # Ensure you're using the correct gradle task to build APK

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run UI Tests (Optional, if you have UI tests)
      run: ./gradlew connectedAndroidTest

    - name: Upload APK as artifact (Optional, if you want to store the APK)
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: app/build/outputs/apk/debug/app-debug.apk  # Ensure this is the correct path for the generated APK

    - name: Upload test results (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/test-results  # Ensure this is the correct path for test results


