name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean Gradle Build
      run: ./gradlew clean

    - name: Verify gradlew file exists
      run: |
        if [ ! -f ./gradlew ]; then
          echo "gradlew file not found!"
          exit 1
        fi

    - name: Build APK
      run: ./gradlew assembleDebug  # Build the APK

    - name: Run Unit Tests
      run: ./gradlew test  # Run unit tests

    - name: Run UI Tests (Optional, if you have UI tests)
      run: ./gradlew connectedAndroidTest
      # If you are not running UI tests, you can comment out or remove this step.

    - name: Debug APK Path
      run: |
        echo "Listing files in APK output directory..."
        ls -R app/build/outputs/apk/debug/  # Ensure this path is correct

    - name: Debug Test Results Path
      run: |
        echo "Listing files in test results directory..."
        ls -R app/build/test-results/  # Ensure this path is correct

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: app/build/outputs/apk/debug/app-debug.apk  # Ensure this is correct

    - name: Upload test results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/test-results  # Ensure this path is correct for your project



