name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean Gradle Build
      run: ./gradlew clean

    - name: Verify gradlew file exists
      run: |
        if [ ! -f ./gradlew ]; then
          echo "gradlew file not found!"
          exit 1
        fi

    - name: Build APK
      run: ./gradlew assembleDebug  # Ensure correct task is used to build APK

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run UI Tests (Optional)
      run: ./gradlew connectedAndroidTest

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: app/build/outputs/apk/debug/app-debug.apk  # Check if this path is correct

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/test-results  # Ensure this path is correct for your test results


