name: Android CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean Gradle Build
      run: ./gradlew clean  # Clean build before starting

    - name: Verify gradlew file exists
      run: |
        if [ ! -f ./gradlew ]; then
          echo "gradlew file not found!"
          exit 1
        fi

